[main]
font=JetBrains Nerd Font:size=12
fuzzey=yes
terminal=foot -e
prompt="❯ "

width=40
lines=8
horizontal-pad=24
vertical-pad=16
inner-pad=10

anchor=center
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
# Deep Dark background with ~85% opacity (d9)
background=15171bd9

# Normal text (Atomic White/Grey)
text=abb2bfff
prompt=abb2bfff
input=abb2bfff
placeholder=5c6370ff

# Matched characters (Atomic Blue)
match=61afefff

# Selected item background (Standard Atomic background)
selection=282c34ff

# Selected item text
selection=282c34ff
selection-text=ffffffff
selection-match=61afefff

[border]
width=0
radius=10

[dmenu]
mode=text
exit-immediately-if-empty=no
